import type { TopicQuiz } from '@/lib/quiz-data';

export const illegalImmigrationQuiz: TopicQuiz = {
  topicId: 'illegal-immigration',
  topicName: 'Illegal Immigration',
  topicTitle: 'Illegal Immigration',
  levels: [
    {
      difficulty: 'easy',
      title: 'Fundamentals',
      description: 'Basic biblical and legal foundations for ordered immigration.',
      passingScore: 70,
      rankEarned: 'Intern Analyst',
      questions: [
        {
          id: 'ii-e1',
          question: 'According to Romans 13:1-2, what is the Christian posture toward governing authorities?',
          options: [
            'Rebel whenever inconvenient',
            'Be subject to authorities God has established',
            'Ignore laws you dislike',
            'Only obey religious leaders',
          ],
          correctIndex: 1,
          explanation: 'Romans 13 teaches that legitimate authority is God-ordained and Christians are called to be subject to governing authorities.',
        },
        {
          id: 'ii-e2',
          question: 'What does Acts 17:26 establish about nations?',
          options: [
            'Borders are man-made fiction',
            'God determined when and where people would live — nations have boundaries',
            'All nations should merge',
            'Only Israel has borders',
          ],
          correctIndex: 1,
          explanation: 'Acts 17:26 shows God ordained nations with times and places — borders and national order are part of His design.',
        },
        {
          id: 'ii-e3',
          question: 'Can compassion for foreigners and respect for immigration law coexist?',
          options: [
            'No — you must choose one',
            'Yes — love foreigners while upholding lawful processes',
            'Only if borders are open',
            'Only for citizens',
          ],
          correctIndex: 1,
          explanation: 'Leviticus 19:33-34 calls us to love foreigners while still maintaining lawful order. Legal immigration honors both principles.',
        },
        {
          id: 'ii-e4',
          question: 'What injustice does illegal immigration create for legal immigrants?',
          options: [
            'None — all immigration is the same',
            'It rewards rule-breakers while those who waited legally are penalized',
            'Legal immigrants support open borders',
            'Legal immigrants face no process',
          ],
          correctIndex: 1,
          explanation: 'Millions wait years and spend thousands to immigrate legally. Rewarding illegal entry is unjust to those who followed the law.',
        },
        {
          id: 'ii-e5',
          question: 'What did Ronald Reagan say about nations and borders?',
          options: [
            '"Open borders build strength"',
            '"A nation that cannot control its borders is not a nation"',
            '"Borders are obsolete"',
            '"Immigration requires no laws"',
          ],
          correctIndex: 1,
          explanation: 'Reagan recognized that border control is essential to national sovereignty and orderly governance.',
        },
        {
          id: 'ii-e6',
          question: 'How does Ruth model proper immigration integration?',
          options: [
            'She refused to adapt',
            'She said "Your people will be my people and your God my God"',
            'She ignored local customs',
            'She returned home immediately',
          ],
          correctIndex: 1,
          explanation: 'Ruth fully adopted the people, customs, and God of her new homeland — a model of lawful assimilation.',
        },
      ],
    },
    {
      difficulty: 'medium',
      title: 'Applied Knowledge',
      description: 'Stewardship, justice, and security arguments for immigration policy.',
      passingScore: 75,
      rankEarned: 'Senior Fellow',
      questions: [
        {
          id: 'ii-m1',
          question: 'What did Milton Friedman warn about immigration and welfare?',
          options: [
            'They always work together',
            'You cannot simultaneously have free immigration and a welfare state',
            'Welfare eliminates immigration',
            'Immigration has no fiscal impact',
          ],
          correctIndex: 1,
          explanation: 'Friedman argued that unlimited immigration combined with expansive welfare creates unsustainable fiscal burdens.',
        },
        {
          id: 'ii-m2',
          question: 'What does Luke 14:28-30 teach about governance?',
          options: [
            'Never plan ahead',
            'Prudent stewardship requires counting the cost before acting',
            'Spend without limits',
            'Avoid all immigration',
          ],
          correctIndex: 1,
          explanation: 'Jesus taught that wise builders count the cost first — nations must govern immigration prudently.',
        },
        {
          id: 'ii-m3',
          question: 'What is a primary security concern with uncontrolled borders?',
          options: [
            'Too many tourists',
            'Inability to vet criminals, traffickers, and security threats',
            'Excess legal workers',
            'Language diversity',
          ],
          correctIndex: 1,
          explanation: 'Without border control, nations cannot properly vet who enters — compromising citizen safety.',
        },
        {
          id: 'ii-m4',
          question: 'How should you respond to "Jesus was a refugee"?',
          options: [
            'Jesus broke immigration laws',
            'His family fled legally to Egypt and returned when safe — no laws were broken',
            'Refugees never need documentation',
            'The Bible opposes all travel',
          ],
          correctIndex: 1,
          explanation: 'The Holy Family\'s flight to Egypt was lawful movement within the Roman Empire, not illegal border crossing.',
        },
        {
          id: 'ii-m5',
          question: 'What does Leviticus 19:15 require in immigration policy?',
          options: [
            'Show favoritism to rule-breakers',
            'Judge fairly without partiality — same rules for all',
            'Ignore legal immigrants',
            'Eliminate all standards',
          ],
          correctIndex: 1,
          explanation: 'Biblical justice demands impartiality — not rewarding some while penalizing those who followed the rules.',
        },
        {
          id: 'ii-m6',
          question: 'What balanced policy approach does the material support?',
          options: [
            'Open borders with no enforcement',
            'No immigration ever',
            'Strong borders, streamlined legal immigration, and humanitarian exceptions',
            'Amnesty for all with no security',
          ],
          correctIndex: 2,
          explanation: 'The position supports border security alongside generous legal immigration and genuine humanitarian processing.',
        },
      ],
    },
    {
      difficulty: 'hard',
      title: 'Strategic Defense',
      description: 'Master counter-arguments and debate strategies on immigration.',
      passingScore: 80,
      rankEarned: 'Chief Strategist',
      questions: [
        {
          id: 'ii-h1',
          question: 'How do you respond to "We\'re all immigrants"?',
          options: [
            'Deny all immigration history',
            'Ancestors largely came legally under laws of their time; laws exist for legitimate reasons today',
            'Agree that laws don\'t matter',
            'Say only natives belong',
          ],
          correctIndex: 1,
          explanation: 'Heritage of legal immigration doesn\'t negate the need for orderly processes that protect citizens and immigrants alike.',
        },
        {
          id: 'ii-h2',
          question: 'How do you address "They do jobs Americans won\'t do"?',
          options: [
            'Ignore labor needs',
            'Legal guest worker programs can address labor needs without undermining rule of law',
            'All jobs should go to illegal workers',
            'End all foreign labor',
          ],
          correctIndex: 1,
          explanation: 'Labor needs can be met through lawful guest worker programs rather than rewarding illegal entry.',
        },
        {
          id: 'ii-h3',
          question: 'What false choice should you reject in immigration debates?',
          options: [
            'Security OR compassion',
            'Law OR love — you can support both lawful order and compassionate treatment',
            'Borders OR welcome',
            'All of the above false choices',
          ],
          correctIndex: 3,
          explanation: 'Reject false dichotomies: compassion and security, law and love, borders and welcome can all coexist through ordered legal immigration.',
        },
        {
          id: 'ii-h4',
          question: 'What did Nehemiah 4 demonstrate about community protection?',
          options: [
            'Prayer alone, no action',
            'Combined prayer with posting guards to protect families',
            'Abandon the wall project',
            'Open all gates',
          ],
          correctIndex: 1,
          explanation: 'Nehemiah prayed AND posted guards — wisdom combines spiritual dependence with practical protection.',
        },
        {
          id: 'ii-h5',
          question: 'What is the assimilation argument\'s core concern about rapid uncontrolled immigration?',
          options: [
            'Too much patriotism',
            'It creates parallel societies rather than unified communities',
            'Immigrants learn English too fast',
            'Cultural exchange is harmful',
          ],
          correctIndex: 1,
          explanation: 'Ordered immigration allows time for integration; uncontrolled flows can fragment communities.',
        },
        {
          id: 'ii-h6',
          question: 'What is the strongest closing frame for immigration debates?',
          options: [
            'Anti-immigrant hostility',
            'Support generous LEGAL immigration while enforcing borders — love AND law',
            'Eliminate all enforcement',
            'Ignore legal immigrants\' sacrifices',
          ],
          correctIndex: 1,
          explanation: 'Lead with support for legal immigration, rule of law, and dignified treatment — opposing illegal entry, not immigrants themselves.',
        },
      ],
    },
  ],
};

export const secondAmendmentQuiz: TopicQuiz = {
  topicId: 'second-amendment',
  topicName: 'Second Amendment',
  topicTitle: 'Second Amendment',
  levels: [
    {
      difficulty: 'easy',
      title: 'Fundamentals',
      description: 'Biblical and constitutional foundations of the right to bear arms.',
      passingScore: 70,
      rankEarned: 'Intern Analyst',
      questions: [
        {
          id: '2a-e1',
          question: 'What did Jesus tell his disciples in Luke 22:36 about self-defense?',
          options: [
            'Never own any weapons',
            'If you don\'t have a sword, sell your cloak and buy one',
            'Only soldiers may be armed',
            'Weapons are always sinful',
          ],
          correctIndex: 1,
          explanation: 'Jesus endorsed self-defense tools as legitimate and even necessary for His disciples.',
        },
        {
          id: '2a-e2',
          question: 'What does Exodus 22:2-3 establish?',
          options: [
            'Homeowners must flee intruders',
            'Justifiable defense of home and family against a nighttime intruder',
            'All violence is forbidden',
            'Only police may defend homes',
          ],
          correctIndex: 1,
          explanation: 'Scripture recognizes the moral right to defend one\'s home and family from violent threats.',
        },
        {
          id: '2a-e3',
          question: 'What does the Second Amendment protect?',
          options: [
            'Only state militias, not individuals',
            'The right of the people to keep and bear arms',
            'Government monopoly on force',
            'Hunting licenses only',
          ],
          correctIndex: 1,
          explanation: 'The Second Amendment explicitly protects "the right of the people to keep and bear Arms."',
        },
        {
          id: '2a-e4',
          question: 'What did DC v. Heller (2008) establish?',
          options: [
            'No individual right to firearms',
            'Individual right to firearm ownership for lawful purposes including self-defense',
            'Only military weapons are protected',
            'States may ban all guns',
          ],
          correctIndex: 1,
          explanation: 'The Supreme Court affirmed an individual right to keep arms for lawful purposes including self-defense.',
        },
        {
          id: '2a-e5',
          question: 'What does 1 Timothy 5:8 say about providing for your household?',
          options: [
            'Only financial provision matters',
            'Failure to provide for your household denies the faith — protection included',
            'Self-defense is optional',
            'Family protection is the government\'s job alone',
          ],
          correctIndex: 1,
          explanation: 'Providing for your household includes protecting them. Disarming citizens removes that God-given ability.',
        },
        {
          id: '2a-e6',
          question: 'What did George Washington say about firearms and liberty?',
          options: [
            'Firearms are unnecessary in free societies',
            'Firearms are the American people\'s "liberty teeth"',
            'Only the military needs guns',
            'Guns cause tyranny',
          ],
          correctIndex: 1,
          explanation: 'Washington called firearms essential to American liberty and independence.',
        },
      ],
    },
    {
      difficulty: 'medium',
      title: 'Applied Knowledge',
      description: 'Practical, historical, and logical arguments for gun rights.',
      passingScore: 75,
      rankEarned: 'Senior Fellow',
      questions: [
        {
          id: '2a-m1',
          question: 'What did CDC research estimate about defensive gun uses annually?',
          options: [
            'Under 1,000',
            '500,000 to 3 million — far exceeding gun homicides',
            'Zero documented cases',
            'Only police use guns defensively',
          ],
          correctIndex: 1,
          explanation: 'CDC estimates show defensive gun uses vastly outnumber criminal gun homicides.',
        },
        {
          id: '2a-m2',
          question: 'What did Warren v. District of Columbia (1981) rule?',
          options: [
            'Police must protect every individual',
            'Police have no specific legal duty to protect individual citizens',
            'Citizens cannot sue police',
            'Guns are banned in DC',
          ],
          correctIndex: 1,
          explanation: 'The court ruled police aren\'t legally obligated to protect individuals — you are ultimately responsible for your safety.',
        },
        {
          id: '2a-m3',
          question: 'What historical pattern preceded 20th-century genocides?',
          options: [
            'Increased civilian gun ownership',
            'Citizen disarmament before mass killing',
            'Stronger militias',
            'Open carry laws',
          ],
          correctIndex: 1,
          explanation: 'Nazi Germany, Soviet Union, Communist China, and Cambodia all disarmed citizens before mass atrocities.',
        },
        {
          id: '2a-m4',
          question: 'What do Switzerland and Israel demonstrate about guns and crime?',
          options: [
            'High gun ownership always means high crime',
            'High gun ownership with strong culture can mean very low crime',
            'Gun bans are the only solution',
            'Culture doesn\'t matter',
          ],
          correctIndex: 1,
          explanation: 'Both nations have high civilian gun ownership and low gun crime — culture and values matter more than bans.',
        },
        {
          id: '2a-m5',
          question: 'What is the key fallacy of gun control according to Thomas Sowell?',
          options: [
            'Guns are too available to criminals',
            'Gun control disarms law-abiding citizens while criminals still get weapons',
            'All guns should be registered',
            'Police need more power',
          ],
          correctIndex: 1,
          explanation: 'Sowell argued gun control laws don\'t control guns — they disarm the law-abiding while criminals remain armed.',
        },
        {
          id: '2a-m6',
          question: 'How should you respond to "turn the other cheek"?',
          options: [
            'Never defend anyone',
            'Jesus addressed personal insults, not violent threats to innocent life',
            'Pacifism in all situations',
            'Only police may use force',
          ],
          correctIndex: 1,
          explanation: 'Turn the other cheek concerns personal insults and retaliation — not defending innocent life from violent attack.',
        },
      ],
    },
    {
      difficulty: 'hard',
      title: 'Strategic Defense',
      description: 'Master counter-arguments and debate strategies on the Second Amendment.',
      passingScore: 80,
      rankEarned: 'Chief Strategist',
      questions: [
        {
          id: '2a-h1',
          question: 'How do you respond to "Only the military needs guns"?',
          options: [
            'Agree completely',
            'Founders intended armed citizens as check against government overreach',
            'Militias are obsolete',
            'The Amendment only applies to 18th-century weapons',
          ],
          correctIndex: 1,
          explanation: 'The Founders explicitly viewed an armed citizenry as essential to preserving liberty against tyranny.',
        },
        {
          id: '2a-h2',
          question: 'How do you address "Other countries have fewer shootings"?',
          options: [
            'America is uniquely violent by nature',
            'Culture, family breakdown, and mental illness drive violence — not gun ownership alone',
            'Copy every foreign gun law',
            'Ignore international comparisons',
          ],
          correctIndex: 1,
          explanation: 'France and Norway have strict gun control yet suffered mass killings. Root causes matter more than tools.',
        },
        {
          id: '2a-h3',
          question: 'What false choice should you reject in gun debates?',
          options: [
            'Guns OR safety',
            'Armed citizens ARE safety — reject the guns-vs-safety framing',
            'Rights OR responsibility',
            'Both A and B',
          ],
          correctIndex: 3,
          explanation: 'Reject false dichotomies: armed citizens provide safety, and rights come with responsibility.',
        },
        {
          id: '2a-h4',
          question: 'What did Benjamin Franklin warn about trading liberty for safety?',
          options: [
            'Safety always wins',
            'Those who give up essential liberty for temporary safety deserve neither',
            'Liberty is overrated',
            'Government should decide both',
          ],
          correctIndex: 1,
          explanation: 'Franklin\'s famous warning applies directly to disarmament proposals sold as "safety" measures.',
        },
        {
          id: '2a-h5',
          question: 'Where does Scripture locate the source of violence?',
          options: [
            'In external tools like guns',
            'In the human heart — "The heart is deceitful above all things"',
            'In poverty alone',
            'In the Second Amendment',
          ],
          correctIndex: 1,
          explanation: 'Jeremiah 17:9 and Mark 7 identify the heart as the source of evil — not inanimate objects.',
        },
        {
          id: '2a-h6',
          question: 'What is the strongest policy focus instead of disarming law-abiding citizens?',
          options: [
            'Ban all firearms immediately',
            'Enforce existing laws, address root causes, and hold criminals accountable',
            'Ignore mental health',
            'Defund police',
          ],
          correctIndex: 1,
          explanation: 'Focus on enforcement, family breakdown, mental illness, and criminal accountability — not punishing lawful gun owners.',
        },
      ],
    },
  ],
};
